export const data = [
  {
    gradeId: 4,
    gradeName: "Grade 1",
    sections: [
      {
        sectionId: 1,
        sectionName: "Section A",
        students: [
          {
            studentId: 1001,
            studentName: "Juan Miguel Antonio Dela Cruz",
            firstName: "Juan Miguel Antonio",
            middleName: "Bonifacio",
            lastName: "Dela Cruz",
            suffix: null,
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
          {
            studentId: 1002,
            studentName: "Maria Santos",
            firstName: "Maria",
            middleName: "Lopez",
            lastName: "Santos",
            suffix: null,
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
        ],
      },
      {
        sectionId: 2,
        sectionName: "Section B",
        students: [
          {
            studentId: 1003,
            studentName: "Jose Rizal",
            firstName: "Jose",
            middleName: "Protacio",
            lastName: "Rizal",
            suffix: null,
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
          {
            studentId: 1004,
            studentName: "Andres Bonifacio",
            firstName: "Andres",
            middleName: null,
            lastName: "Bonifacio",
            suffix: null,
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
        ],
      },
      {
        sectionId: 3,
        sectionName: "Section C",
        students: [
          {
            studentId: 1005,
            studentName: "Emilio Aguinaldo",
            firstName: "Emilio",
            middleName: null,
            lastName: "Aguinaldo",
            suffix: null,
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
          {
            studentId: 1006,
            studentName: "Apolinario Mabini",
            firstName: "Apolinario",
            middleName: null,
            lastName: "Mabini",
            suffix: null,
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
        ],
      },
    ],
  },
  {
    gradeId: 5,
    gradeName: "Grade 2",
    sections: [
      {
        sectionId: 4,
        sectionName: "Section A",
        students: [
          {
            studentId: 1007,
            studentName: "Corazon Aquino",
            firstName: "Corazon",
            middleName: null,
            lastName: "Aquino",
            suffix: null,
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
          {
            studentId: 1008,
            studentName: "Benigno Aquino III",
            firstName: "Benigno",
            middleName: null,
            lastName: "Aquino",
            suffix: "III",
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
          {
            studentId: 1009,
            studentName: "Ferdinand Marcos Jr.",
            firstName: "Ferdinand",
            middleName: null,
            lastName: "Marcos",
            suffix: "Jr.",
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
          {
            studentId: 1010,
            studentName: "Leni Robredo",
            firstName: "Leni",
            middleName: null,
            lastName: "Robredo",
            suffix: null,
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
        ],
      },
      {
        sectionId: 5,
        sectionName: "Section B",
        students: [
          {
            studentId: 1011,
            studentName: "Miriam Defensor Santiago",
            firstName: "Miriam",
            middleName: "Defensor",
            lastName: "Santiago",
            suffix: null,
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
          {
            studentId: 1012,
            studentName: "Ninoy Aquino",
            firstName: "Ninoy",
            middleName: null,
            lastName: "Aquino",
            suffix: null,
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
        ],
      },
      {
        sectionId: 6,
        sectionName: "Section C",
        students: [
          {
            studentId: 1013,
            studentName: "Lito Lapid",
            firstName: "Lito",
            middleName: null,
            lastName: "Lapid",
            suffix: null,
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
          {
            studentId: 1014,
            studentName: "Robin Padilla",
            firstName: "Robin",
            middleName: null,
            lastName: "Padilla",
            suffix: null,
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
        ],
      },
    ],
  },
  {
    gradeId: 6,
    gradeName: "Grade 3",
    sections: [
      {
        sectionId: 7,
        sectionName: "Section A",
        students: [
          {
            studentId: 1015,
            studentName: "Alfredo Lim",
            firstName: "Alfredo",
            middleName: null,
            lastName: "Lim",
            suffix: null,
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
          {
            studentId: 1016,
            studentName: "Isko Moreno",
            firstName: "Isko",
            middleName: null,
            lastName: "Moreno",
            suffix: null,
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
        ],
      },
      {
        sectionId: 8,
        sectionName: "Section B",
        students: [
          {
            studentId: 1017,
            studentName: "Erap Estrada",
            firstName: "Erap",
            middleName: null,
            lastName: "Estrada",
            suffix: null,
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
          {
            studentId: 1018,
            studentName: "Joseph Estrada",
            firstName: "Joseph",
            middleName: null,
            lastName: "Estrada",
            suffix: null,
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
        ],
      },
      {
        sectionId: 9,
        sectionName: "Section C",
        students: [
          {
            studentId: 1019,
            studentName: "Grace Poe",
            firstName: "Grace",
            middleName: null,
            lastName: "Poe",
            suffix: null,
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
          {
            studentId: 1020,
            studentName: "Manny Pacquiao",
            firstName: "Manny",
            middleName: null,
            lastName: "Pacquiao",
            suffix: null,
            applicationStatus: "Enrolled",
            enrollmentDate: new Date("2023-06-15"),
          },
        ],
      },
      {
        sectionId: 10,
        sectionName: "Section D",
        students: [],
      },
    ],
  },
];
