import Enums from "@/services/common/types/enums";

export const data = [
  {
    gradeId: 4,
    gradeName: "Grade 1",
    sections: [
      {
        sectionId: 1,
        sectionName: "Section A",
        students: [
          {
            studentId: 1001,
            firstName: "Paolo Benigno",
            middleName: "Aguirre",
            lastName: "Aquino",
            suffix: "IV",
            enrollmentStatus: Enums.application_status.pending,
            requirements: [
              {
                applicationId: 1,
                requirementId: 1,
                requirementName: "Birth Certificate",
                requirementType: Enums.attachment_type.image,
                requirementStatus: Enums.attachment_status.pending,
                fileUrl: null,
                fileName: null,
                userInput: null,
              },
              {
                applicationId: 1,
                requirementId: 2,
                requirementName: "Report Card",
                requirementType: Enums.attachment_type.image,
                requirementStatus: Enums.attachment_status.pending,
                fileUrl: null,
                fileName: null,
                userInput: null,
              },
            ],
          },
          {
            studentId: 1002,
            firstName: "Francis Pancratius",
            middleName: "Nepomuceno",
            lastName: "Pangilinan",
            suffix: null,
            enrollmentStatus: Enums.application_status.pending,
            requirements: [
              {
                applicationId: 2,
                requirementId: 1,
                requirementName: "Birth Certificate",
                requirementType: Enums.attachment_type.image,
                requirementStatus: Enums.attachment_status.pending,
                fileUrl: null,
                fileName: null,
                userInput: null,
              },
              {
                applicationId: 2,
                requirementId: 2,
                requirementName: "Good Moral Certificate",
                requirementType: Enums.attachment_type.image,
                requirementStatus: Enums.attachment_status.pending,
                fileUrl: null,
                fileName: null,
                userInput: null,
              },
            ],
          },
        ],
      },
      {
        sectionId: 2,
        sectionName: "Section B",
        students: [
          {
            studentId: 1003,
            firstName: "Heidi",
            middleName: "Reyes",
            lastName: "Lloce",
            suffix: null,
            enrollmentStatus: Enums.application_status.pending,
            requirements: [
              {
                applicationId: 3,
                requirementId: 1,
                requirementName: "Birth Certificate",
                requirementType: Enums.attachment_type.image,
                requirementStatus: Enums.attachment_status.pending,
                fileUrl: null,
                fileName: null,
                userInput: null,
              },
              {
                applicationId: 3,
                requirementId: 2,
                requirementName: "Medical Clearance",
                requirementType: Enums.attachment_type.image,
                requirementStatus: Enums.attachment_status.pending,
                fileUrl: null,
                fileName: null,
                userInput: null,
              },
            ],
          },
          {
            studentId: 1004,
            firstName: "Ana Theresia",
            middleName: "Navarro",
            lastName: "Hontiveros",
            suffix: null,
            enrollmentStatus: Enums.application_status.pending,
            requirements: [
              {
                applicationId: 4,
                requirementId: 1,
                requirementName: "Birth Certificate",
                requirementType: Enums.attachment_type.image,
                requirementStatus: Enums.attachment_status.pending,
                fileUrl: null,
                fileName: null,
                userInput: null,
              },
              {
                applicationId: 4,
                requirementId: 2,
                requirementName: "Vaccination Card",
                requirementType: Enums.attachment_type.image,
                requirementStatus: Enums.attachment_status.pending,
                fileUrl: null,
                fileName: null,
                userInput: null,
              },
              {
                applicationId: 4,
                requirementId: 3,
                requirementName: "Mother's Name",
                requirementType: Enums.attachment_type.text,
                requirementStatus: Enums.attachment_status.pending,
                fileUrl: null,
                fileName: null,
                userInput: "Maria Leonor Gerona Robredo",
              },
            ],
          },
        ],
      },
      {
        sectionId: 3,
        sectionName: "Section C",
        students: [],
      },
    ],
  },
];
